### ISSUE TITLE
Dockerfile of vm_mon is not working

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-monitor-probe#32]
in Dockerfile:
`COPY ./vm_mon/ /opt/Monitoring`

the source directory should be changed since Dockerfile is already in ./vm_mon

**Comment by pkarkazis** [comment]
Hi @stevenvanrossem,
dockerfiles are written in order to build the probes from parent directory (son-monitor-probes/).
You can use the command:
docker build -f sp_mon/Dockerfile -t son-monitor-probe .

**Comment by stevenvanrossem** [comment]
ah ok I see, I didn't think of specifying the path with the Dockerfile, thnks!
